USE digital_smart_class;
INSERT IGNORE INTO course_categories(name) VALUES
('Programming'),('Networking'),('Cybersecurity'),('Databases'),('Mobile Development'),('Artificial Intelligence');
INSERT IGNORE INTO app_settings(setting_key,setting_value) VALUES ('completion_percent','90');
-- Admin and accountant accounts are created at first start by DataSeeder (BCrypt hashes are generated by the app).
